package convertidores;

import calculos.Temperatura;
import javax.swing.JOptionPane;

public class ConvertidorTemperatura extends javax.swing.JFrame {
    
    
    String de, a;
    double ingresa;
    
    Temperatura calcular = new Temperatura();

    /**
     * Creates new form ConvertidorTemperatura
     */
    public ConvertidorTemperatura() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Convertidor de Temperatura");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ingresarCantidad = new javax.swing.JTextField();
        resultadoConversion = new javax.swing.JTextField();
        DE = new javax.swing.JComboBox<>();
        A = new javax.swing.JComboBox<>();
        Convertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(496, 252));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ingresar Temperatura");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Resultado");

        ingresarCantidad.setPreferredSize(new java.awt.Dimension(45, 20));
        ingresarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarCantidadActionPerformed(evt);
            }
        });

        resultadoConversion.setPreferredSize(new java.awt.Dimension(45, 20));
        resultadoConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoConversionActionPerformed(evt);
            }
        });

        DE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Celsius", "Fahrenheit", "Kelvin" }));
        DE.setMinimumSize(new java.awt.Dimension(45, 20));
        DE.setPreferredSize(new java.awt.Dimension(45, 20));
        DE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEActionPerformed(evt);
            }
        });

        A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        A.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Celsius", "Fahrenheit", "Kelvin" }));
        A.setMinimumSize(new java.awt.Dimension(45, 20));
        A.setPreferredSize(new java.awt.Dimension(45, 20));
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        Convertir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Convertir.setText("Convertir");
        Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Convertir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ingresarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(A, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultadoConversion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(ingresarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(resultadoConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Convertir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        MenuPrincipal newframe = new MenuPrincipal();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void ingresarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarCantidadActionPerformed

    }//GEN-LAST:event_ingresarCantidadActionPerformed

    private void resultadoConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoConversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoConversionActionPerformed

    private void DEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEActionPerformed
        de = DE.getSelectedItem().toString();

    }//GEN-LAST:event_DEActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        a = A.getSelectedItem().toString();
    }//GEN-LAST:event_AActionPerformed

    private void ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirActionPerformed

        Double ingresa = Double.parseDouble(ingresarCantidad.getText());

        switch (de){
            
            case ("Ninguna"):
               
               JOptionPane.showMessageDialog(this, "Seleccionar Temperatuta");
               
            break;
            case ("Celsius"):
            if(a.equals("Kelvin")){
                resultadoConversion.setText(Double.toString(calcular.celciusKelvin(ingresa)));
            }else if(a.equals("Fahrenheit")){
                resultadoConversion.setText(Double.toString(calcular.celciusFahrenheit(ingresa)));
            
            }else {
                JOptionPane.showMessageDialog(this, "Seleccionar otro tipo de grados");
            }
            break;
            case ("Fahrenheit"):
            if(a.equals("Celsius")){
                resultadoConversion.setText(Double.toString(calcular.fahrenheitCelcius(ingresa)));
            }else if(a.equals("Kelvin")){
                resultadoConversion.setText(Double.toString(calcular.fahrenheitKelvin(ingresa)));
            }else {
                JOptionPane.showMessageDialog(this, "Seleccionar otro tipo de grados");
            }
            break;
            case ("Kelvin"):
            if(a.equals("Celsius")){
                resultadoConversion.setText(Double.toString(calcular.kelvinCelcius(ingresa)));
            }else if(a.equals("Fahrenheit")){
                resultadoConversion.setText(Double.toString(calcular.kelvinFahrenheit(ingresa)));
            }else {
                JOptionPane.showMessageDialog(this, "Seleccionar otro tipo de grados");
            }
            break;
            default:
            JOptionPane.showMessageDialog(this, "Tipo de grados no diponible");

        }
    }//GEN-LAST:event_ConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertidorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertidorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertidorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertidorTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertidorTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> A;
    private javax.swing.JButton Convertir;
    private javax.swing.JComboBox<String> DE;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField ingresarCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField resultadoConversion;
    // End of variables declaration//GEN-END:variables
}
